FROM golang:1.12-alpine

RUN apk add --no-cache git

# Set the Current Working Directory inside the container
WORKDIR /app/prioritaria_server

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

# Build the Go app
RUN go build -o ./out/gpsNt20 gpsNt20.go


# This container exposes port 8080 to the outside world
EXPOSE 7098

# Run the binary program produced by `go install`
CMD ["./out/gpsNt20"]